[project]
name = "dpbuild"
version = "0.1.0"
authors = [{ name = "David Thigpen", email = "davidthigs@gmail.com" }]
description = "A library for bundling Minecraft datapacks"
readme = "README.md"
requires-python = ">=3.8"
